### ISSUE TITLE
Byline's left border on blog entry gets very long on mobile

### ISSUE THREAD

**Issue by mhk-y** [ucsb/UCSBWebTheme.Drupal8#3]
![image](https://user-images.githubusercontent.com/34074171/124995205-dba8f300-dffb-11eb-8b77-11e6feb13010.png)

**Comment by rvizena** [comment]
@mhk-y Link to your multidev site:
http://issue-03-collab-ucsb-web-theme-v01.pantheonsite.io/user

**Comment by mhk-y** [comment]
I have fixed the issue and push the changes to the Issue-03 multidev.
You can see the fix on this test blog: https://issue-03-collab-ucsb-web-theme-v01.pantheonsite.io/web-theme/mihokos-bolg

**Comment by mhk-y** [comment]
I also included the gitignore file change in this issue fix. 
We are now ignoring lando.yml file.

**Comment by rvizena** [comment]
Issue-03 has been merged into the Custom Upstream. Thanks!
